apiVersion: v1
kind: Service 
metadata:
  name: spring-service
spec:
  selector:
    spring: ecom
  type: NodePort
  ports:
    - protocol: TCP
      ports: 8009
      nodePort: 30011
      targetPort: 8009  
  
